routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome2');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/**
 * Users / Employee
 */
Route::prefix('user')->name('user.')->namespace('UserManagement')->group(function() {
    Route::delete('/{user_id}/destroy', 'UserController@destroy')->name('destroy');
    Route::put('/{user_id}/update', 'UserController@update')->name('update');
    Route::get('/{user_id}/edit', 'UserController@edit')->name('edit');
    Route::post('/store', 'UserController@store')->name('store');
    Route::get('/create', 'UserController@create')->name('create');
    Route::get('/get/user', 'UserController@getUser')->name('getUser');
    Route::get('/', 'UserController@index')->name('index');
});

/**
 * Uploads
 */
Route::prefix('upload')->name('upload.')->namespace('Data')->group(function() {
    Route::delete('/{upload_id}/destroy', 'UploadController@destroy')->name('destroy');
    Route::put('/{upload_id}/update', 'UploadController@update')->name('update');
    Route::get('/{upload_id}/edit', 'UploadController@edit')->name('edit');
    Route::post('/store', 'UploadController@store')->name('store');
    Route::get('/create', 'UploadController@create')->name('create');
    Route::get('/', 'UploadController@index')->name('index');
});

app/Http/Controllers/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\UserManagement;

use App\Traits\FlashMessage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use App\Model\UserManagement\Entities\User;

class UserController extends Controller
{

    use FlashMessage;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users  = User::orderBy('updated_at', 'DESC')->paginate(10);

        return view('users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nik'       => 'required|unique:users,nik',
            'name'      => 'required',
            'email'     => 'required|unique:users,email',
            'phone'     => 'required',
            'password'  => 'required',
            'address'   => 'required'
        ]);

        $user           = new User();
        $user->nik      = $request->get('nik');
        $user->name     = $request->get('name');
        $user->email    = $request->get('email');
        $user->phone    = $request->get('phone');
        $user->password = Hash::make($request->get('password'));
        $user->address  = $request->get('address');
        $user->save();

        return redirect()->route('user.create')->with(self::success('Employee has been added!'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($user_id)
    {
        $user   = User::find($user_id);

        return view('users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $user_id)
    {
        $request->validate([
            'nik'       => 'required|unique:users,nik,'.$user_id.',id',
            'name'      => 'required',
            'email'     => 'required|unique:users,email,'.$user_id.',id',
            'phone'     => 'required',
            'address'   => 'required'
        ]);

        $user           = User::find($user_id);
        $user->nik      = $request->get('nik');
        $user->name     = $request->get('name');
        $user->email    = $request->get('email');
        $user->phone    = $request->get('phone');
        $user->address  = $request->get('address');
        $user->save();

        return redirect()->route('user.edit', ['user_id' => $user->id])->with(self::success('Data employee has beed updated!'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($user_id)
    {
        try {
            DB::beginTransaction();
            $user   = User::query()->where('id', $user_id)->firstOrFail();
            $user->delete();
            DB::commit();

            return redirect()->back()->with(self::warning('Data has been deleted!'));
        } catch (\Throwable $th) {
            DB::rollback();
            return redirect()->back()->with(self::danger('Data cannot deleted from database!'));
        }
    }

    public function getUser(Request $request)
    {
        $keyword = $request->get('q');
        $users = User::where('name', 'like', "%$keyword%")->get();
        return $users;
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Karyawan')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah Karyawan</div>

                <div class="card-body">

                    @include('partials.message')

                    <form class="needs-validation" novalidate method="POST" action="{{ route('user.store') }}">
                        @csrf
                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">NIK</label>
                          <div class="col-sm-10">
                            <input type="text" name="nik" onkeyup="validNumber(this)" class="form-control" required>
                            @error('nik')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Name</label>
                          <div class="col-sm-10">
                            <input type="text" name="name" class="form-control" required>
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Email</label>
                          <div class="col-sm-10">
                            <input type="email" name="email" class="form-control" required>
                            @error('email')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">No. HP</label>
                            <div class="col-sm-10">
                              <input type="text" name="phone" onkeyup="validNumber(this)" class="form-control" required>
                              @error('phone')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Password</label>
                            <div class="col-sm-10">
                              <input type="password" name="password" value="rahasia" class="form-control" required>
                              <small class="form-text text-muted">
                                  Password default : <code>rahasia</code>
                              </small>
                              @error('password')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Address</label>
                            <div class="col-sm-10">
                              <textarea name="address" class="form-control" rows="3" required></textarea>
                              @error('address')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                          <div class="col-sm-10">
                              <button type="submit" class="btn btn-success">Save</button>
                              <a href="{{ route('user.index') }}" class="btn btn-secondary">Back</a>
                          </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
function validNumber(num)
{
    if(!/^[0-9.]+$/.test(num.value))
    {
        num.value = num.value.substring(0, num.value.length-1000);
    }
}

(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
@endpush

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Karyawan')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Karyawan</div>

                <div class="card-body">

                    @include('partials.message')

                    <form class="needs-validation" novalidate method="POST" action="{{ route('user.update', ['user_id' => $user->id]) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">NIK</label>
                          <div class="col-sm-10">
                            <input type="text" name="nik" value="{{ $user->nik }}" onkeyup="validNumber(this)" class="form-control" required>
                            @error('nik')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Name</label>
                          <div class="col-sm-10">
                            <input type="text" name="name" value="{{ $user->name }}" class="form-control" required>
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Email</label>
                          <div class="col-sm-10">
                            <input type="email" name="email" value="{{ $user->email }}" class="form-control" required>
                            @error('email')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">No. HP</label>
                            <div class="col-sm-10">
                              <input type="text" name="phone" value="{{ $user->phone }}" onkeyup="validNumber(this)" class="form-control" required>
                              @error('phone')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Address</label>
                            <div class="col-sm-10">
                              <textarea name="address" class="form-control" rows="3" required>{{ $user->address }}</textarea>
                              @error('address')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                          <div class="col-sm-10">
                              <button type="submit" class="btn btn-success">Save</button>
                              <a href="{{ route('user.index') }}" class="btn btn-secondary">Back</a>
                          </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
function validNumber(num)
{
    if(!/^[0-9.]+$/.test(num.value))
    {
        num.value = num.value.substring(0, num.value.length-1000);
    }
}

(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
@endpush

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Karyawan')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Data Karyawan</div>

                <div class="card-body">
                    @include('partials.message')

                    <p>
                        <a href="{{ route('user.create') }}" class="btn btn-success">Tambah Karyawan</a>
                    </p>

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">NIK</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">No. HP</th>
                                <th scope="col">Alamat</th>
                                <th scope="col">Action</th>
                              </tr>
                            </thead>
                            <tbody>
                              @foreach ($users as $item => $user)
                                  <tr>
                                      <td>{{ $item + 1 }}</td>
                                      <td>{{ $user->nik }}</td>
                                      <td>{{ $user->name }}</td>
                                      <td>{{ $user->email }}</td>
                                      <td>{{ $user->phone }}</td>
                                      <td>{{ $user->address }}</td>
                                      <td>
                                        <a href="{{ route('user.edit', ['user_id' => $user->id]) }}" class="btn btn-info btn-sm">Edit</a>
                                        <form method="POST" action="{{ route('user.destroy', ['user_id' => $user->id]) }}"
                                            onsubmit="return confirm('Are you sure to delete this user of {{ $user->name }}?')">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                                        </form>
                                      </td>
                                  </tr>
                              @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="10">{{ $users->links() }}</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection