routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome2');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/**
 * Users / Employee
 */
Route::prefix('user')->name('user.')->namespace('UserManagement')->group(function() {
    Route::delete('/{user_id}/destroy', 'UserController@destroy')->name('destroy');
    Route::put('/{user_id}/update', 'UserController@update')->name('update');
    Route::get('/{user_id}/edit', 'UserController@edit')->name('edit');
    Route::post('/store', 'UserController@store')->name('store');
    Route::get('/create', 'UserController@create')->name('create');
    Route::get('/get/user', 'UserController@getUser')->name('getUser');
    Route::get('/', 'UserController@index')->name('index');
});

/**
 * Uploads
 */
Route::prefix('upload')->name('upload.')->namespace('Data')->group(function() {
    Route::delete('/{upload_id}/destroy', 'UploadController@destroy')->name('destroy');
    Route::put('/{upload_id}/update', 'UploadController@update')->name('update');
    Route::get('/{upload_id}/edit', 'UploadController@edit')->name('edit');
    Route::post('/store', 'UploadController@store')->name('store');
    Route::get('/create', 'UploadController@create')->name('create');
    Route::get('/', 'UploadController@index')->name('index');
});

app/Http/Controllers/Data/UploadController.php
<?php

namespace App\Http\Controllers\Data;

use Carbon\Carbon;
use App\Traits\UploadTrait;
use Illuminate\Support\Str;
use App\Traits\FlashMessage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Model\Data\Entities\Upload;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class UploadController extends Controller
{
    use FlashMessage, UploadTrait;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $uploads     = Upload::orderBy('updated_at', 'DESC')->paginate(10);

        return view('uploads.index', ['uploads' => $uploads]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('uploads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $now            = 0;
        $dateFormat     = str_replace('-', '', $now);
        $countTable     = Upload::count();
        $sequence       = str_pad($countTable + 1, 0, '0', STR_PAD_LEFT);

        $upload             = new Upload();
        $upload->register   = 'REG - '.$dateFormat.$sequence;
        $upload->date       = $request->get('date');
        $upload->user_id    = $request->get('user');
        $upload->company    = $request->get('company');
        $upload->perumahan  = $request->get('perumahan');
        $upload->unit_total = $request->get('unit_total');
        $upload->ket        = $request->get('ket');
        if ($request->has('file')) {
            $file       = $request->file('file');
            $name       = 'REG - '.$dateFormat.$sequence;
            $folder     = '/uploads/';
            $filepath   = $folder.$name.'.'.$file->getClientOriginalExtension();
            $this->userUpload($file, $folder, 'public', $name);
            $upload->file = $filepath;
        }
        $upload->save();

        return redirect()->route('upload.create')->with(self::success('Data has been uploaded!'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($upload_id)
    {
        $upload     = Upload::find($upload_id);

        return view('uploads.edit', ['upload' => $upload]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $upload_id)
    {
        $request->validate([
            'register'      => 'required|unique:uploads,register,'.$upload_id.',id',
            'date'          => 'required',
            'user'          => 'required',
            'company'       => 'required',
            'perumahan'     => 'required',
            'unit_total'    => 'required',
            'ket'           => 'required'
        ]);

        $upload             = Upload::find($upload_id);
        $upload->register   = $request->get('register');
        $upload->date       = $request->get('date');
        $upload->user_id    = $request->get('user');
        $upload->company    = $request->get('company');
        $upload->perumahan  = $request->get('perumahan');
        $upload->unit_total = $request->get('unit_total');
        $upload->ket        = $request->get('ket');
        if ($request->has('file')) {
            $this->userDeleteFileUpload($upload->file);
            $file       = $request->file('file');
            $name       = $upload->register;
            $folder     = '/uploads/';
            $filepath   = $folder.$name.'.'.$file->getClientOriginalExtension();
            $this->userUpload($file, $folder, 'public', $name);
            $upload->file = $filepath;
        }
        $upload->save();

        return redirect()->route('upload.edit', ['upload_id' => $upload->id])->with(self::success('Data has been uploaded!'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($upload_id)
    {
        try {
            DB::beginTransaction();
            $upload     = Upload::query()->where('id', $upload_id)->firstOrFail();
            if (!empty($upload->file)) {
                $this->userDeleteFileUpload($upload->file);
            }
            $upload->delete();

            DB::commit();
            return redirect()->back()->with(self::warning('Data has been deleted!'));
        } catch (\Throwable $th) {
            DB::rollback();
            return redirect()->back()->with(self::danger('Data cannot deleted from database!'));
        }
    }
}

resources/views/uploads/create.blade.php
@extends('layouts.app')
@section('title', 'Tambah Register')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah Register</div>

                <div class="card-body">

                    @include('partials.message')

                    <form class="needs-validation" novalidate method="POST" action="{{ route('upload.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Tanggal</label>
                          <div class="col-sm-10">
                            <input type="text" name="date" class="form-control" id="date" required>
                            @error('date')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Nama Surveyor</label>
                          <div class="col-sm-10">
                            <select class="form-control" style="width: 100%" id="user" name="user">
                            </select>
                            @error('user')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Company</label>
                          <div class="col-sm-10">
                            <input type="text" name="company" class="form-control" required>
                            @error('company')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Nama Perumahan</label>
                            <div class="col-sm-10">
                              <input type="text" name="perumahan" class="form-control" placeholder="" required>
                              @error('company')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                          </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Jumlah Unit</label>
                            <div class="col-sm-10">
                              <input type="text" name="unit_total" onkeyup="validNumber(this)" class="form-control" required>
                              @error('unit_total')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Keterangan</label>
                            <div class="col-sm-10">
                              <input type="text" name="ket" class="form-control" placeholder="Jika kosong inputkan ' - '" required>
                              @error('company')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                          </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">File Resume</label>
                            <div class="col-sm-10">
                              <input type="file" name="file" class="form-control" accept="application/pdf" required>
                              @error('file')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                          <div class="col-sm-10">
                              <button type="submit" class="btn btn-success">Add</button>
                              <a href="{{ route('upload.index') }}" class="btn btn-secondary">Back</a>
                          </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
function validNumber(num)
{
    if(!/^[0-9.]+$/.test(num.value))
    {
        num.value = num.value.substring(0, num.value.length-1000);
    }
}

(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

$('#date').flatpickr({
    dateFormat: "Y-m-d",
})

$('#user').select2({
    ajax: {
        url:  '{{ route('user.getUser') }}',
        processResults: function (data) {
            return {
                results: data.map(function (item) {
                    return {
                        id: item.id,
                        text: item.name
                    }
                })
            }
        }
    }
});
</script>
@endpush

resources/views/uploads/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Register')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Register</div>

                <div class="card-body">

                    @include('partials.message')

                    <form class="needs-validation" novalidate method="POST" action="{{ route('upload.update', ['upload_id' => $upload->id]) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Kode Register</label>
                          <div class="col-sm-10">
                            <input type="text" name="register" value="{{ $upload->register }}" class="form-control" required>
                            @error('register')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Tanggal</label>
                          <div class="col-sm-10">
                            <input type="text" name="date" value="{{ $upload->date }}" class="form-control" id="date" required>
                            @error('date')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Nama Surveyor</label>
                          <div class="col-sm-10">
                            <select class="form-control" style="width: 100%" id="user" name="user">
                                <option value="{{ $upload->user_id }}" selected>{{ $upload->user->name }}</option>
                            </select>
                            @error('user')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                          <label class="col-sm-2 col-form-label">Company</label>
                          <div class="col-sm-10">
                            <input type="text" name="company" value="{{ $upload->company }}" class="form-control" required>
                            @error('company')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Nama Perumahan</label>
                            <div class="col-sm-10">
                              <input type="text" name="perumahan" value="{{ $upload->perumahan }}" class="form-control" placeholder="" required>
                              @error('company')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                          </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Jumlah Unit</label>
                            <div class="col-sm-10">
                              <input type="text" name="unit_total" value="{{ $upload->unit_total }}" onkeyup="validNumber(this)" class="form-control" required>
                              @error('unit_total')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Keterangan</label>
                            <div class="col-sm-10">
                              <input type="text" name="ket" value="{{ $upload->ket }}"class="form-control" placeholder="Jika kosong inputkan ' - '" required>
                              @error('company')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                          </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">File Resume</label>
                            <div class="col-sm-10">
                              <input type="file" name="file" class="form-control" accept="application/pdf">
                              @error('file')
                              <div class="invalid-feedback">
                                  {{ $message }}
                              </div>
                              @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                          <div class="col-sm-10">
                              <button type="submit" class="btn btn-success">Save</button>
                              <a href="{{ route('upload.index') }}" class="btn btn-secondary">Back</a>
                          </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
function validNumber(num)
{
    if(!/^[0-9.]+$/.test(num.value))
    {
        num.value = num.value.substring(0, num.value.length-1000);
    }
}

(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

$('#date').flatpickr({
    dateFormat: "Y-m-d",
})

$('#user').select2({
    ajax: {
        url:  '{{ route('user.getUser') }}',
        processResults: function (data) {
            return {
                results: data.map(function (item) {
                    return {
                        id: item.id,
                        text: item.name
                    }
                })
            }
        }
    }
});
</script>
@endpush

resources/views/uploads/index.blade.php
@extends('layouts.app')
@section('title', 'Data Register')
@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Data Register</div>

                <div class="card-body">
                    @include('partials.message')

                    <p>
                        <a href="{{ route('upload.create') }}" class="btn btn-success">Tambah Register</a>
                    </p>

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">Kode Register</th>
                                <th scope="col">Nama Surveyor</th>
                                <th scope="col">Tanggal</th>
                                <th scope="col">Company</th>
                                <th scope="col">Perumahan</th>
                                <th scope="col">Jumlah Unit</th>
                                <th scope="col">Keterangan</th>
                                <th scope="col">File Resume</th>
                                <th scope="col">QR Code</th>
                                <th scope="col">Action</th>
                              </tr>
                            </thead>
                            <tbody>
                              @foreach ($uploads as $item => $upload)
                                <tr>
                                    <td>{{ $item + 1 }}</td>
                                    <td>{{ $upload->register }}</td>
                                    <td>{{ $upload->user->name }}</td>
                                    <td>{{ date('d-m-Y', strtotime($upload->date)) }}</td>
                                    <td>{{ $upload->company }}</td>
                                    <td>{{ $upload->perumahan }}</td>
                                    <td>{{ $upload->unit_total}}</td>
                                    <td>{{ $upload->ket}}</td>
                                    <td><a href="{{ asset('storage'. $upload->file) }}" target="_blank">{{ basename('storage'.$upload->file) }}</a></td>
                                    <td><img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge('https://i.pinimg.com/originals/38/47/25/384725cbdf156d2f76ff17b1a14f93dd.png', 0.3, true)
                                        ->size(180)->errorCorrection('H')
                                        ->generate(asset('storage' .$upload->file))) !!} "></td>
                                    <td>
                                    <td>
                                        <a href="{{ route('upload.edit', ['upload_id' => $upload->id]) }}" class="btn btn-info btn-sm">Edit</a>
                                        <form method="POST" action="{{ route('upload.destroy', ['upload_id' => $upload->id]) }}"
                                            onsubmit="return confirm('Are you sure to delete this data of {{ $upload->register }}?')">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                              @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    {{ $uploads->links() }}
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection